using System.Text.Json.Serialization;

namespace Cerebras.Cloud.Sdk.Chat;

/// <summary>
/// Represents a chat completion choice.
/// </summary>
public record ChatChoice
{
    /// <summary>
    /// The index of this choice.
    /// </summary>
    public required int Index { get; init; }

    /// <summary>
    /// The message generated by the model.
    /// </summary>
    public required ChatMessage Message { get; init; }

    /// <summary>
    /// The reason the generation stopped.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; init; }

    /// <summary>
    /// Log probabilities for the output tokens.
    /// </summary>
    public object? Logprobs { get; init; }
}